name: Analyze Pull Request

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]

jobs:
  analyzeWithMaven:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: zulu
      - name: Setup Maven
        uses: gradle/gradle-build-action@v2
      - name: Build with Maven
        run: mvn clean install
      - name: Execute Tests
        run: mvn test